# Identificamos el lenguaje
language: node_js

# Indicamos la plataforma de destino
node_js:
  - 12.16.3

  # Decimos los servicios a usar desde tyravis al exterior
services:
  – mongodb
# Instalamos las dependencias de la app
install:
  - npm ci

# Ejecutamos los comandos
script:
  # Hacemos Lint al código y corregimos sus errores automaticamente si puede, si no error
  - npm run lint-ci
  # - printenv >> .env
  # - npm test
  # Costruimos los ficheros ejecutables
  - npm run build-travis --if-present

# Solo actuamos antes cambios en el master
branches:
  only:
    - master
