language: node_js
node_js:
  - 12.16.3
services:
  – mongodb
install:
  - npm ci

script:
  - npm run lint
  # - printenv >> .env
  # - npm test
  - npm run build --if-present
branches:
  only:
    - master
