language: node_js
node_js:
  - 12.16.3
services:
  – mongodb
install:
  - npm ci

script:
  - npm run lint
  ## - npm run test
  - printenv >> .env
  - echo .env
  ## - npm run build --if-present
branches:
  only:
    - master
