# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          ENV: ${{ secrets.ENV }}
          DEBUG: ${{ secrets.DEBUG }}
          HOST: ${{ secrets.ENV }}
          PORT: ${{ secrets.PORT }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          TOKEN_LIFE: ${{ secrets.TOKEN_LIFE }}
          TOKEN_REFRESH: ${{ secrets.TOKEN_REFRESH }}
          BC_SALT: ${{ secrets.BC_SALT }}
          DB_DEBUG: ${{ secrets.DB_DEBUG }}
          DB_POOLSIZE: ${{ secrets.DB_POOLSIZE }}
          DB_PROTOCOL: ${{ secrets.DB_PROTOCOL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FILE_SIZE: ${{ secrets.FILE_SIZE }}
          FILES_PATH: ${{ secrets.FILES_PATH }}
          FILES_URL: ${{ secrets.FILES_URL }}

      - run: echo $FILES_URL
      - run: npm ci
      - run: npm install
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
