# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci

     # - name: lint
     # - run: npm run lint
      - run: |
          printenv >> .env
          echo .env
     # - run: npm test
        env:
          ENV: development
          DEBUG: true
          PORT: 8000
          TIMEZONE: Europe/Madrid
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          TOKEN_LIFE: 40
          TOKEN_REFRESH: 60
          BC_SALT: 10
          DB_POOLSIZE: 200
          DB_PROTOCOL: ${{ secrets.DB_PROTOCOL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FILE_SIZE: 2
          FILES_PATH: files
          FILES_URL: filles
      #
      #
      #
      # - run: npm run build --if-present
      #
